### ISSUE TITLE
PIL module is a python requirement 

### ISSUE THREAD

**Issue by EricDeveaud** [rrwick/Trycycler#18]
Hello

while installing Trycycler-0.5.0 I noticed that PIL(pillow) is not in the python moudles requirement 

regards

Eric

**Comment by rrwick** [comment]
Thanks - I had `PIL` in the `requirements.txt` file, but I think it should have been `pillow`. That one confuses me because the package name and the import name are different. Just changed it: 7d3aba2. Thanks!
