### ISSUE TITLE
Docker request

### ISSUE THREAD

**Issue by ConstantinV** [rrwick/Trycycler#2]
Hello,
May I ask you to create a Docker image for your brilliant pipeline!

Thank you.

**Comment by kapsakcj** [comment]
I've made a docker image that you are welcome to use: https://hub.docker.com/r/staphb/trycycler

Just a heads up though, this is not endorsed or supported by the author of this tool...If you run into any issues with the docker image specifically, please leave a github issue over at the repo where we house our Dockerfiles: https://github.com/StaPH-B/docker-builds

I've tested it using the "Great" demo dataset that Ryan graciously provided and it produced nearly identical output to what he has in the example output for the analysis of the demo dataset. Only differences were small things like the STDOUT reporting of version numbers for the R packages, but the actual outputs (consensus assemblies and such) were identical.

Another heads up, this docker image only contains the necessary dependencies for trycycler itself, it does not have the other helpful/associated tools (flye, wtdbg2/redbean, filtlong, seqtk, etc). Though we have most of those tools packaged in separate docker images.

There is also a docker image that was generated by bioconda/biocontainers, though that conda recipe includes trycycler 0.3.1, whereas my docker image has the latest version 0.3.3 https://bioconda.github.io/recipes/trycycler/README.html?highlight=trycycler#package-Recipe%20&#x27;trycycler&#x27;

Cheers,
Curtis

**Comment by rrwick** [comment]
Thanks, @kapsakcj! I was procrastinating on Docker/Conda because I figured Trycycler would change a fair bit in the near future. But I appreciate you filling that void! I hope to come back to this in the future and make an 'official' Docker container and Bioconda recipe.

**Comment by ConstantinV** [comment]
Dear @kapsakcj, thank you so much for the detailed information! I will definitely try your docker  image!
@rrwick, thank you. It will be great if you make it!
