### ISSUE TITLE
failed circularisation

### ISSUE THREAD

**Issue by hbadrane** [rrwick/Trycycler#25]
What if the contig is not circular? like just a chromosome... How to be able to proceed without having to circularize?

**Comment by rrwick** [comment]
If your replicon is linear, then use the `--linear` option for the `trycycler reconcile` and `trycycler consensus` steps. That will make it skip any circularisation-related steps in the process.

If your replicon _might_ be linear, but you're not sure, I'd recommend running `trycycler dotplot` ([see here](https://github.com/rrwick/Trycycler/wiki/Reconciling-contigs#dotplots)). If all the contigs in the cluster are starting/ending at the same place, that's a decent clue that you've got a linear replicon.

Ryan
