### ISSUE TITLE
Trycycler or Unicycler when plasmids are expected?

### ISSUE THREAD

**Issue by termithorbor** [rrwick/Trycycler#26]
Hi,

is Trycycler or Unicycler a better option when you expect that the strain of interest has at least one plasmid?

Thanks in advance.

**Comment by rrwick** [comment]
If you have good long read depth, then I think Trycycler is generally better than Unicycler, and that includes for plasmid assembly. The one caveat might be small plasmids, which can sometimes be troublesome for long-read assemblers. And [depending on the DNA prep](https://doi.org/10.1099/mgen.0.000631), small plasmids can be underrepresented in long read sets.

So if you want to be thorough, I'd say try both! Use Trycycler+polishing for the majority of your assembly, but then check to see if any small plasmids are in the Unicycler assembly which the Trycycler assembly might have missed.

Also, I'm assuming you're talking about a strain for which you have hybrid reads (both long and short). If you have long reads only, then you shouldn't use Unicycler - newer long-read assemblers (e.g. Flye) are better.

For a more verbose answer, I'd encourage you to check out the [Guide to bacterial genome assembly](https://github.com/rrwick/Trycycler/wiki/Guide-to-bacterial-genome-assembly) on Trycycler's wiki.
