### ISSUE TITLE
version.py of 0.5.2 is still 0.5.1

### ISSUE THREAD

**Issue by pvstodghill** [rrwick/Trycycler#27]
I think perhaps you forgot the version bump before releasing 0.5.2. Took me a couple of minutes to figure out why version 0.5.1 was still on my path after installing 0.5.2. :-)

**Comment by rrwick** [comment]
Good catch! What a silly mistake 😳 

I've just made v0.5.3, and now the code version and the GitHub version definitely match.

Thanks!
