### ISSUE TITLE
Short and long reads come from different samples

### ISSUE THREAD

**Issue by termithorbor** [rrwick/Trycycler#31]
Hi,

I have already ask the question in Unicycler - sorry for that.

What would be the best approach for assembling the genome when the short and long reads come from different samples (same strain but different DNA isolations)?

Thanks in advance :)

**Comment by rrwick** [comment]
Since Trycycler is a long-read-only assembly approach, I'll answer thise question over on the Unicycler issues page (https://github.com/rrwick/Unicycler/issues/289) and close this one.

Ryan
