### ISSUE TITLE
Command 'raven' not found

### ISSUE THREAD

**Issue by Chuangsc** [rrwick/Trycycler#33]
Hello, 

I had installed trycycler through conda. But when I ran raven for one subset of reads, it showed that not found "raven" command. Later, I tried to installed Raven through conda (conda install -c bioconda raven-assembler), it still didn't work. Could you kindly help me to solve the problem? Thanks much!

**Comment by MostafaYA** [comment]
Hello, 
I tried this installtion and it worked 
```
git clone https://github.com/lbcb-sci/raven && cd raven
cmake -S ./ -B./build -DRAVEN_BUILD_EXE=1 -DCMAKE_BUILD_TYPE=Release 
cmake --build build
```

If needed, you may call the full path to raven if it is not in your $PATH

**Comment by rrwick** [comment]
I too have had success building Raven as @MostafaYA described. It compiles to a single executable file (`build/bin/raven`) so I copy this file to somewhere that is already in my `$PATH` (I use `~/.local/bin` for things like this).

Ryan
