### ISSUE TITLE
KeyError thrown in 'Merging MSA' step of trycycler msa

### ISSUE THREAD

**Issue by AshSies** [rrwick/Trycycler#35]
Hi there, 

I am running Trycycler 0.5.3, and near the end of the msa step in the pipeline, I am getting a KeyError thrown with certain clusters. In the environment I have set up, the msa makes use of MUSCLE v5.1. The traceback directs me to line 175 in msa.py: 

_line 175, in merge_pieces
    aligned_seq_parts[n].append(parts[n].upper())
KeyError: 'A_contig_1'_

This has only been an issue with clusters including larger (> 2 Mb) contigs. Other clusters with smaller tigs, produced from the same 'trycycler cluster' step and assemblers, have worked just fine.

Any input would be appreciated - thank you for your time!

**Comment by kclambi1** [comment]
I also have this same issue with the same error flag.  Large bacterial contigs, about 5.4mb each.  All good up until the MSA merging step.

**Comment by VMJarocki** [comment]
I believe I am also getting this error:

 File "/home/user/Data/miniconda3/envs/trycycler/bin/trycycler", line 10, in <module>
    sys.exit(main())
  File "/home/user/Data/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/__main__.py", line 51, in main
    msa(args)
  File "/home/user/Data/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/msa.py", line 36, in msa
    merge_pieces(temp_dir, args.cluster_dir, seqs)
  File "/home/user/Data/miniconda3/envs/trycycler/lib/python3.9/site-packages/trycycler/msa.py", line 175, in merge_pieces
    aligned_seq_parts[n].append(parts[n].upper())
KeyError: 'C_Utg936'

**Comment by VMJarocki** [comment]
@kclambi1 @AshSies @sgblanch were any of you able to resolve this issue?

**Comment by AshSies** [comment]
Using Muscle 3.8 also resolved the issue on my end.

**Comment by kclambi1** [comment]
This is strange, as version 0.5.2 added support for muscle versions 3.x and 5.x.

**Comment by abomba** [comment]
Muscle crash when has too long sequence to align and run out of memory.  Different between version 3 and 5 is that muscle 5 create empty file with msa even when crash. Trycycler checking this step only by looking for lacks of msa files so when you use version 5 everything looks fine.  It should chcek also if files is empty . If you want avoid running out of memmory try change `--lookahead` to smaller value, this should affect to max piece size in partitioning step and therefore on memmory usage by muscle.

`def check_muscle_results(temp_dir: pathlib.Path, piece_count):
    missing_files = []
    for i in range(piece_count):
        muscle_out_filename = temp_dir / f'{i:012d}_msa.fasta'
        if not muscle_out_filename.is_file():
            missing_files.append(muscle_out_filename)
    if missing_files:
        sys.exit(f'Error: MUSCLE failed to complete on {len(missing_files)} of the {piece_count} '
                 f'pieces. Please remove the most divergent sequences from this cluster and then '
                 f'try again.')
`

**Comment by rrwick** [comment]
Thanks to everyone here for the investigation!

I've just pushed (42be6d7) a small fix to the problem that @abomba pointed out, so Trycycler will now recognise empty MUSCLE files as being problematic. This should at least result in better error messages.

I've also made a note on [the Software Requirements page of the wiki](https://github.com/rrwick/Trycycler/wiki/Software-requirements#muscle) to say that MUSCLE v3 is preferred.

**Comment by rrwick** [comment]
@marade in #42 pointed out that Muscle v5 defaults to lots of threads, and Trycycler runs many instances of Muscle, so this may explain the out-of-memory issues. I've just pushed a fix (886fdd5) which limits Muscle v5 to one thread per instance to help with this, but I still recommend Muscle v3 for speed.
