### ISSUE TITLE
MUSCLE version compatibility issue?

### ISSUE THREAD

**Issue by fgaudilliere** [rrwick/Trycycler#38]
Hi there!

First of all, thank you for all the work you put into making Trycycler and all your other tools as easy to use as possible. 

I just wanted to let you know that I ran into an issue trying to use Trycycler with the latest version of MUSCLE. The default version on my lab's cluster is version 5.1, and it seems to mess up the `trycycler msa` step. I kept getting the following error: 

> Error: MUSCLE failed to complete on 4988 of the 4988 pieces. Please remove the most divergent sequences from this cluster and then try again.

I solved it by loading MUSCLE v.3.8.31 instead. 

Best, 
Flora

**Comment by rrwick** [comment]
Hi Flora,

Are you using the latest version of Trycycler? I updated it in v0.5.2 to work with MUSCLE v5, and I just double checked on two computers (my Mac laptop and a Linux server), and it seems to be working (for me anyway).

That being said, MUSCLE v3 seems to be much faster than MUSCLE v5, so you might want to stick with the older version anyway. See more here: https://github.com/rrwick/Trycycler/wiki/FAQ-and-miscellaneous-tips#a-note-on-muscle-versions

Ryan

**Comment by fgaudilliere** [comment]
Hi Ryan, 

I checked, and our version is v0.5.0, so this explains that. Thanks for the clarification! (Sorry, I hadn't read that part of the wiki)

Best, 
Flora
