### ISSUE TITLE
muscle command in msa.py missing -threads argument

### ISSUE THREAD

**Issue by marade** [rrwick/Trycycler#42]
The lines in question are:

muscle_command = ['muscle', '-in', input_filename, '-out', output_filename]

muscle_command = ['muscle', '-align', input_filename, '-output', output_filename]

Since the multiprocessing module is already controlling threads here, and muscle defaults to using all cores (up to 20), if you specify `trycycler msa --threads 16`  it will try to use num_cores*16 threads instead of just 16, yes?

**Comment by rrwick** [comment]
Thanks - that's a good catch! It seems to only affect Muscle v5 (I don't think Muscle v3) uses threads when aligning. This may also explain the memory issues described in #35.

I've just pushed a fix for this (886fdd5), though in my testing, this only improves memory usage, not runtime. So despite the fix, I still find Muscle v3 to be much faster, so I recommend users stick with the old version ([read more here](https://github.com/rrwick/Trycycler/wiki/FAQ-and-miscellaneous-tips#a-note-on-muscle-versions)).

Ryan
