### ISSUE TITLE
Strange clustering/a lot of clusters

### ISSUE THREAD

**Issue by termithorbor** [rrwick/Trycycler#43]
Hi,

how would you go on in a case linke this when quite a lot of clusters are found?

![image](https://user-images.githubusercontent.com/66436023/191254334-a1e1cba8-2ac5-4992-b059-23f18a42737b.png)

**Comment by rrwick** [comment]
Oof - that's a real mess! My first thought, based on the contig lengths, is that your input assemblies are not complete. This is a requirement of Trycycler, i.e. you can't use draft assemblies as input. What species is this?

I also find the branch lengths in your screenshot to be odd. It looks like a cladogram where branch lengths are ignored, but branch lengths are important for interpreting the cluster tree. What tool are you using to view the tree? I usually use [FigTree[(http://tree.bio.ed.ac.uk/software/figtree).

Ryan

**Comment by derekstein** [comment]
I am having the same issue, my genome should be 1.1m. If my genome is expected to be 1.1m should contig lengths also be 1.1m as well?

**Comment by rrwick** [comment]
You should expect contig lengths that mostly match the lengths of your replicons. For example, if your genome has a 1.1 Mbp chromosome and a 60 kbp plasmid, contigs would ideally either be 1.1 Mbp or 60 kbp. It's normal if some contigs don't fit (e.g. fragmentation, poor circularisation, contamination, etc). But if lots/most of your contigs don't fit, that suggests a bigger problem (e.g. read length is too short for complete assembly).

Ryan
