### ISSUE TITLE
Please make new bug fix release to get fixes into bioconda

### ISSUE THREAD

**Issue by corneliusroemer** [rrwick/Trycycler#49]
Hey! It's nice you fixed some bugs recently. I noticed that the bug fixes haven't yet propagated into bioconda.

It would be great if you could make a release so the fixes end up there! Thanks!

**Comment by rrwick** [comment]
Done! Trycycler v0.5.4 is now released, and the [conda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/trycycler/meta.yaml) has been updated :smile:
