### ISSUE TITLE
Too Many Clusters

### ISSUE THREAD

**Issue by derekstein** [rrwick/Trycycler#50]
How many clusters should I be generating? Is ~160 clusters too many? No matter how much QC I do my tree looks a lot like the final example and I can't seem to find a single cluster that fits the length of my genome (for reference it's 1.1m). None of my clusters seem to be 1.1m bp, they tend to be 100k-300k bp

**Comment by rrwick** [comment]
Ideally, you have just one cluster per replicon. Often there are a few more clusters that need to be discarded. But yes, I'm afraid that 160 clusters is _way_ too many.

Without seeing your data, my best guess is that your read set is simply insufficient to assemble the genome well, e.g. reads are too short or depth is too shallow. A lot of heterogeneity in the read set could also cause problems. If you really need a nice completed genome, I suspect you'll need to re-sequence 😢 

Ryan
