### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by songmj86** [rrwick/Trycycler#53]
Hi 

I would like to ask whether trycycler is applicalbe on short-read-assembled contigs as I have multiple contigs assembled from different assemblers and they are originated from illumina hiseq data.

I am looking forward to hearing you

Thanks!

**Comment by rrwick** [comment]
Sorry, but Trycycler is only appropriate for genomes which can be completed, i.e. each replicon can be assembled into a single contig. And for short-read data, that is almost certainly not the case - your assembly will be fragmented.

However, if your genome _can_ be completed with short-read data (e.g. a viral genome or a very simple bacterial genome), then Trycycler might be possible. But I haven't tried myself!

Ryan
