### ISSUE TITLE
I have a problem with spades.py 

### ISSUE THREAD

**Issue by lil-bei-bei** [rrwick/Trycycler#57]
== Running: /Users/yewensheng/opt/anaconda3/envs/Unicycler/bin/spades-hammer /Users/yewensheng/Desktop/015_bar03/assembly_mix/spades_assembly/read_correction/corrected/configs/config.info

  0:00:00.000     1M / 7M    INFO    General                 (main.cpp                  :  75)   Starting BayesHammer, built from refs/heads/master, git revision 54bed604152fd271b68bdf7b78bfd0788ea9e431
  0:00:00.000     1M / 7M    INFO    General                 (main.cpp                  :  76)   Loading config from /Users/yewensheng/Desktop/015_bar03/assembly_mix/spades_assembly/read_correction/corrected/configs/config.info
  0:00:00.011     1M / 7M    INFO    General                 (main.cpp                  :  78)   Maximum # of threads to use (adjusted due to OMP capabilities): 8
  0:00:00.039     1M / 7M    ERROR   General                 (memory_limit.cpp          :  47)   setrlimit(2) call failed, errno = 22

== Error ==  system call for: "['/Users/yewensheng/opt/anaconda3/envs/Unicycler/bin/spades-hammer', '/Users/yewensheng/Desktop/015_bar03/assembly_mix/spades_assembly/read_correction/corrected/configs/config.info']" finished abnormally, OS return value: 22

In case you have troubles running SPAdes, you can write to spades.support@cab.spbu.ru
or report an issue on our GitHub repository github.com/ablab/spades
Please provide us with params.txt and spades.log files from the output directory.

SPAdes log can be found here: /Users/yewensheng/Desktop/015_bar03/assembly_mix/spades_assembly/read_correction/spades.log

Thank you for using SPAdes!

**Comment by rrwick** [comment]
An issue with SPAdes is outside the scope of this repository, so I'm going to close this one. However, based on the error message, it looks like it might be an issue with memory. Does your computer have enough memory to run this? I'd also recommend you try running SPAdes on its own (i.e. not in Unicycler) to see if it gives you the same error.
