### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'minimap2'

### ISSUE THREAD

**Issue by yusator** [rrwick/Trycycler#58]
I have minimap2 installed in my Linux Ubuntu desktop. However, it is not on PATH, so I have to go directly into the folder to launch it. Despite executing trycycler in the minimap2 folder itself, it says it cannot locate it.

**Comment by rrwick** [comment]
If you can, I'd recommend copying the `minimap2` executable file to somewhere in your `PATH` variable - that will make it easier to run in general. But if that's not an option, you can temporarily add it like this before running Trycycler:
```bash
export PATH=/your/path:"$PATH"
```
Replace `/your/path` with the full path of where your `minimap2` file is.

Hope that helps!

**Comment by yusator** [comment]
Thank you for the advice. I did that but then a new error showed up of "PermissionError: [Errno 13] Permission denied: 'minimap2'". Im not sure how trycycler accesses permissions of the file

**Comment by rrwick** [comment]
You could give it maximum permissions like this:
```
chmod 777 minimap2
```
Does that fix it?
