### ISSUE TITLE
Recommendation: LJA / La Jolla Assembler

### ISSUE THREAD

**Issue by MrTomRod** [rrwick/Trycycler#66]
I have had good experiences with LJA (La Jolla Assembler; [GitHub](https://github.com/AntonBankevich/LJA), [paper](https://www.nature.com/articles/s41587-022-01220-6)) on bacterial genomes. It only works for HiFi reads and is based on de Bruijn graphs. It was programmed by Anton Bankevich (from SPADES) and Andrey Bzikadze.

- It circularizes very well
- It never duplicates plasmids
- It is _very_ fast, which is great for the trycycler workflow

The easiest way of getting it to work is using my Docker container: https://hub.docker.com/r/troder/lja

I suggest you try it out and add it to your list of recommended assemblers!

**Comment by rrwick** [comment]
Thanks - I've added a note to the bottom of the [Generating assemblies](https://github.com/rrwick/Trycycler/wiki/Generating-assemblies) page. And I'll give it a try next time I'm using HiFi reads!
