### ISSUE TITLE
Conda installation on Mac not working 

### ISSUE THREAD

**Issue by francescodc87** [rrwick/Trycycler#67]
I am trying to install Trycycler via Conda on a Mac and it is not working..

(trycycler) fxxxxxx@xxxxxx ~ % conda install -c bioconda -c conda-forge trycycler
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 

It is stuck at the last step for hours

**Comment by ctberezin** [comment]
I am having a similar issue, and I believe it's due to incompatibilities between new arm64 mac systems and the Edlib package. I get the same error from conda, and here is the tail end of my error from the pip installation route:

```
Building wheels for collected packages: Trycycler, edlib
  Building wheel for Trycycler (pyproject.toml) ... done
  Created wheel for Trycycler: filename=Trycycler-0.5.4-py3-none-any.whl size=2752908 sha256=d5919d9185aef7f1177ec0b654539a3defbd8104ed97077295e1afdd132f9812
  Stored in directory: /private/var/folders/dk/shj7yjz13jnbrdb6bntm64yh0000gp/T/pip-ephem-wheel-cache-ok9fcpf5/wheels/67/62/7a/7251924133aa18c39f79a6880c2268a475f2ddbe41157199c6
  Building wheel for edlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for edlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'edlib' extension
      creating build
      creating build/temp.macosx-14.0-arm64-cpython-311
      creating build/temp.macosx-14.0-arm64-cpython-311/edlib
      creating build/temp.macosx-14.0-arm64-cpython-311/edlib/src
      clang -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Iedlib/include -I/Users/csniffin/.pyenv/versions/3.11.6/include/python3.11 -c edlib.bycython.cpp -o build/temp.macosx-14.0-arm64-cpython-311/edlib.bycython.o -O3 -std=c++11
      edlib.bycython.cpp:198:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for edlib
Successfully built Trycycler
Failed to build edlib
ERROR: Could not build wheels for edlib, which is required to install pyproject.toml-based projects
```

There is a related [open issue](https://github.com/Martinsos/edlib/issues/212) on the edlib github that hasn't received attention since January.

**Comment by rrwick** [comment]
Frustratingly, the edlib package requires an older version of Python: 3.10 or earlier. So I think if you try installing Trycycler on Python 3.10, it should work, even on an ARM Mac.

I've updated Trycycler on [Bioconda](https://bioconda.github.io/recipes/trycycler/README.html) to specify Python versions, so hopefully that will help with installation!

Ryan
