### ISSUE TITLE
Fails to build under Python 3.12

### ISSUE THREAD

**Issue by mesti90** [rrwick/Trycycler#71]
I tried to install Trycycler with the following command:

    pip3 install --break-system-packages git+https://github.com/rrwick/Trycycler.git

Unfortunately it didn't work. When the installer tried to installed the edlib package, it missed longintrepr.h
I use python 3.12

**Comment by rrwick** [comment]
Glad the workaround fixed it! The edlib package has issues with newer versions of Python, so if anyone else has this issue, I would recommend trying Python 3.10.

Ryan
