### ISSUE TITLE
Question about purpose of subsampling

### ISSUE THREAD

**Issue by aharring83** [rrwick/Trycycler#73]
Hi Dr. Wick,
Why do we need to subsample ONT data for monoisolate genome assembly. I did some benchmarking analysis using rasusa and found that when I subsample by various fractions of trimmed reads, there was no significant difference on my genome assembly using flye. The only exception was when I subsampled to 20% or less of my trimmed reads. I tried to find an explanation in the literature but could not find any and was hoping you could help me understand the purpose of this step. Your response will be greatly appreciated.
Anthony Harrington

**Comment by rrwick** [comment]
Hi Anthony,

I don't think you _need_ to do the read subsampling step. But when running Trycycler, it's good to have lots of input assemblies that are as independent as possible, and read subsampling can help with that in a few ways. Some examples:
* If you're using six different assemblers and you don't subsample your reads, you can only generate six different input assemblies. But if you subsample the reads, you can generate as many different inputs as you want. How independent these assemblies are from each other depends on the depth of the original read set - see [this wiki page](https://github.com/rrwick/Trycycler/wiki/How-read-subsampling-works).
* If there is one read which is strange in some way (e.g. a chimera), it might have the potential to cause a misassembly in multiple assemblers. But with subsampling, that read will not be present in all subsamples, so some assemblies will not be affected by it.
* If you have 500x depth of sequencing for your genome, that may cause assembly to fail (especially with Flye). But the subsampled sets will be ~80x deep, and Flye performs much better at that depth.

I pretty much always use subsampling unless I'm starting with a read set that has not-great depth, e.g. 30x.

When you say 'there was no significant difference on my genome assembly' - I suspect there were still _some_ differences, i.e. the assemblies weren't base-for-base identical. And when there are differences between assemblies, that creates bubbles in the graph (see [step 6 here](https://github.com/rrwick/Trycycler/wiki/Illustrated-pipeline-overview)) where Trycycler can choose the best option.

Ryan
