### ISSUE TITLE
Option for the required software path

### ISSUE THREAD

**Issue by ASUQ** [rrwick/Trycycler#74]
I am using Trycycler from a conda environment and faced
```
Error: unable to determine Mash version - make sure that Mash is correctly installed, then try again.
```
while running `trycycler cluster`.
Could you add the option for the required software as you did in Unicycler?

**Comment by rrwick** [comment]
Sorry, but I'm probably not going to make any big changes to Trycycler going forward, as I'm working on a new tool which will replace Trycycler.

Do I correctly understand that you have Mash but not in your PATH variable, so Trycycler can't find it? If so, I think the easiest solutions would be one of the following:
* Copy the `mash` executable to somewhere in your PATH, e.g. `/usr/local/bin`.
* Temporarily add Mash's path to your PATH variable before running Trycycler: `export PATH=/path/to/mash_dir/:"$PATH"`

Do either of those work?

Ryan

**Comment by ASUQ** [comment]
Thanks for the reply, Ryan

It seems that mash is not correctly installed via conda envirionment.
I got this error when running ```trycycler cluster```, I got
```
Error: unable to determine Mash version - make sure that Mash is correctly installed, then try again.
```

After installing Mash from https://github.com/marbl/Mash and add into the path (```export PATH=/path/to/mash_dir/:"$PATH"```), it worked!

**Comment by rrwick** [comment]
Glad to hear it!
