### ISSUE TITLE
polypolish need polish

### ISSUE THREAD

**Issue by DingJingZhi** [rrwick/Trycycler#75]
polypolish consensus.fasta alignments_1.sam alignments_2.sam > polypolish.fasta

shoud be
polypolish polish  consensus.fasta alignments_1.sam alignments_2.sam > polypolish.fasta

**Comment by rrwick** [comment]
Thanks! I've updated the [polishing page](https://github.com/rrwick/Trycycler/wiki/Polishing-after-Trycycler) to have current commands for both Polypolish and Pypolca.
