### ISSUE TITLE
Capture output of trycycler cluster (feature/help request) 

### ISSUE THREAD

**Issue by muntean-alex** [rrwick/Trycycler#79]
Hello,

Let me start off praising your amazing work! 

As I'm not a bioinformaticion, I'm more often than not working on data on small times away from the (microbiological) workbench. 
I'd like to make my life a little easier and be able to run a directory's worth of fastqs through subsetting, assembling and clustering. I find the output from `trycycler cluster` very helpful along with the newick tree to guide my cluster reconciliation. 
I'd like to save the output `trycycler cluster` to something like a `trycycler.log`, but piping to a file or using `script - c` doesn't work.

Any insight would help alot!
Many thanks in advance!
Alex

**Comment by rrwick** [comment]
Hi Alex,

Trycycler outputs its logging information to [stderr](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)), not stdout, so you'll need to use `2>` to redirect it to a file. For example:
```bash
trycycler cluster --assemblies assemblies/*.fasta --reads reads.fastq.gz --out_dir trycycler 2> trycycler_cluster.log
```

If you want to strip out the text formatting for a cleaner log file, you can add this sed command:
```bash
trycycler cluster --assemblies assemblies/*.fasta --reads reads.fastq.gz --out_dir trycycler 2>&1 | sed 's/\x1b\[[0-9;]*m//g' > trycycler_cluster_no_colours.log
```

I also wrote about this on [Polypolish's FAQ](https://github.com/rrwick/Polypolish/wiki/FAQ-and-miscellaneous-tips#saving-polypolishs-log-to-file), so check out that for some more details!

Ryan
