### ISSUE TITLE
trycyclyer reconcile circularizing some but not all contigs. 

### ISSUE THREAD

**Issue by osvatic** [rrwick/Trycycler#80]
I am trying to use trycycler on a circular bacterial genome and the reconcile step on the largest cluster is only circularizing 2/5 contigs and failing in general. If there a way for the circularized results to still be written even if all contigs are not circularized?

Brief rundown:
I have 5 total contigs in the cluster and they are all ~5.9Mb.

During the reconcile step I get passed the "Initial check of contigs" and "Normalizing strands". 
In the "Circularization" step I get the following:
```
Circularising A_contig_1:
  using B_contig_1:
    unable to circularise: A_contig_1's start/end is the same as B_contig_1's start/end
  using C_contig_1:
    unable to circularise: A_contig_1's start could not be found in C_contig_1
  using D_contig_1:
    unable to circularise: A_contig_1's start could not be found in D_contig_1
  using E_contig_2:
    unable to circularise: A_contig_1's start/end is the same as E_contig_2's start/end
Failed to circularise sequence A_contig_1 for multiple reasons.

Circularising B_contig_1:
  using A_contig_1:
    unable to circularise: B_contig_1's start/end is the same as A_contig_1's start/end
  using C_contig_1:
    unable to circularise: B_contig_1's start could not be found in C_contig_1
  using D_contig_1:
    unable to circularise: B_contig_1's start could not be found in D_contig_1
  using E_contig_2:
    unable to circularise: B_contig_1's start/end is the same as E_contig_2's start/end
Failed to circularise sequence B_contig_1 for multiple reasons.

Circularising C_contig_1:
  using A_contig_1:
    circularising C_contig_1 by trimming 2270807 bp of sequence from the end
  using B_contig_1:
    circularising C_contig_1 by trimming 2270807 bp of sequence from the end
  using D_contig_1:
    unable to circularise: C_contig_1's start/end is the same as D_contig_1's start/end
  using E_contig_2:
    circularising C_contig_1 by trimming 2270807 bp of sequence from the end
  circularisation complete (3,591,523 bp)

Circularising D_contig_1:
  using A_contig_1:
    circularising D_contig_1 by trimming 2270805 bp of sequence from the end
  using B_contig_1:
    circularising D_contig_1 by trimming 2270805 bp of sequence from the end
  using C_contig_1:
    unable to circularise: D_contig_1's start/end is the same as C_contig_1's start/end
  using E_contig_2:
    circularising D_contig_1 by trimming 2270805 bp of sequence from the end
  circularisation complete (3,591,523 bp)

Circularising E_contig_2:
  using A_contig_1:
    unable to circularise: E_contig_2's start/end is the same as A_contig_1's start/end
  using B_contig_1:
    unable to circularise: E_contig_2's start/end is the same as B_contig_1's start/end
  using C_contig_1:
    unable to circularise: E_contig_2's start could not be found in C_contig_1
  using D_contig_1:
    unable to circularise: E_contig_2's start could not be found in D_contig_1
Failed to circularise sequence E_contig_2 for multiple reasons.


Error: the following sequences failed to circularise: A_contig_1, B_contig_1, E_contig_2. Please repair or exclude these
sequences and then try running trycycler reconcile again.

```

So contigs A_contig_1, B_contig_1, E_contig_2 are all the basically the same and therefore can be fixed. But C_contig_1 and D_contig_1 are circularized within this step using A_contig_1, B_contig_1, E_contig_2. Removing these issue contigs makes the reconcile step fail and C_contig_1 and D_contig_1 also have the same start/end as eachother. 

Any clear way to fix this? I had to increase the add_seq and trim_seq to 2500000 which is clearly extreme so it could be that all of this is invalid in the end.

**Comment by rrwick** [comment]
Yeah, something is definitely going wrong with the trimming - you shouldn't need to set `--max_trim_seq` to such a high value! Also, the 'start could not be found' messages are a bit worrying - they imply that the ends of the contigs may not be good. Are you sure this is a circular chromosome, not linear?

I think part of the problem may be that all five contigs seem to be from the same assembler (Flye?), which is why many are starting/ending at the same position. Can you get complete assemblies from other tools? That often helps `trycycler reconcile` perform better.

Ryan

**Comment by osvatic** [comment]
Thanks for the comment. I figured that was extreme for the max_trim_seq.

It is definitely a circular chromosome (bacterial culture) but all of the contigs were made using Flye from subsets of the same assembly. Trying other tools seems like the way to go for now.
